### ISSUE TITLE
Need for a glossary for all the concepts not explained in text

### ISSUE THREAD

**Issue by RadhikaKaul** [worldbank/d4di#111]
From Leo:
> Can we add at least one sentence for each concept (either when it is introduced or creating a glossary)? For example, Github has a link attached to it. However, Github is just one of the many servers. We should provide a justification for why we specifically choose Github over other servers.
 Need at least one line explanations for the following in Ch 2:
- Pre-analysis Plan
- PII encryption
- de-identification of data

**Comment by luizaandrade** [comment]
There's a longer list of items to add definitions to in #32. It would be great to aggregate this on a single issue. Let's talk about it on Friday.

**Comment by RadhikaKaul** [comment]
PII was already defined so didn't include it in the aggregated glossary but others have been transferred.
