### ISSUE TITLE
Intro: Why DIME Wiki is "detailed but unstructured"?

### ISSUE THREAD

**Issue by RadhikaKaul** [worldbank/d4di#113]
From Radhika: 

> Why would mention that DIME is detailed but unstructured? Is it only for the purposes of establishing that RAs/PIs/FCs should go through this book along with going through our open-source portal which may be difficult to navigate just by virtue of it having so much information or is it a different intention.

https://github.com/worldbank/d4di/blob/ff1d6a77bdd48f235b1e6723d7da8ba74047a0ce/chapters/introduction.tex#L69

**Comment by mariaruth** [comment]
removed this language in re-write
