### ISSUE TITLE
Ch2: Why having less than 200 lines in do-files important

### ISSUE THREAD

**Issue by RadhikaKaul** [worldbank/d4di#120]
Can this be explained further? Why is this an important rule of thumb?

https://github.com/worldbank/d4di/blob/ff1d6a77bdd48f235b1e6723d7da8ba74047a0ce/chapters/planning-data-work.tex#L193

**Comment by kbjarkefur** [comment]
Anything longer is difficult to browse, and a limit of 100 lines is often too short.

**Comment by kbjarkefur** [comment]
Add some text where this number is from, and explain it is quite arbitrary
