### ISSUE TITLE
Ch2: Assumption that people practice having two different folders

### ISSUE THREAD

**Issue by RadhikaKaul** [worldbank/d4di#121]
Why is there an assumption here that they should know the difference between project folder and code folder? And how does 'iefolder' help solve the problem of differing structures?

https://github.com/worldbank/d4di/blob/ff1d6a77bdd48f235b1e6723d7da8ba74047a0ce/chapters/planning-data-work.tex#L246

**Comment by kbjarkefur** [comment]
because code is in GitHub, and everything else data, budget document, firm contracts, etc is not a part of your data work and should not be in the same folder
