### ISSUE TITLE
Ch6 : Different paragraphs for data cleaning and data construction

### ISSUE THREAD

**Issue by RadhikaKaul** [worldbank/d4di#128]
We should structure the paragraphs such that the reader knows exactly how **data cleaning** is different from **data construction**.

https://github.com/worldbank/d4di/blob/ff1d6a77bdd48f235b1e6723d7da8ba74047a0ce/chapters/data-analysis.tex#L133-L145

**Comment by kbjarkefur** [comment]
https://github.com/worldbank/d4di/blob/ff1d6a77bdd48f235b1e6723d7da8ba74047a0ce/chapters/data-analysis.tex#L133-L136

I have read these lines a few times now and still do not understand what it means.

**Comment by luizaandrade** [comment]
Radhika's point is addressed in #269
