### ISSUE TITLE
Intro: Introduction YP edits 

### ISSUE THREAD

**Issue by ypowers1** [worldbank/d4di#131]
- Need to rewrite org structure due to new changes? "The DIME Analytics team works within the Development Impact Evaluation unit (DIME), at the World Bank's Development Economics group (DEC)."
- Provide a few examples in definition of "primary data" in sidebar and explain how it relates to "field experiments"
- Define "administrative data" and "big data"
- Pg. 12 1st full paragraph, starting with "(In part this had saved...": this second half of the paragraph is confusing as it jumps from field work is about working with many different types of people to saving time/not having enough time to devote to new recruits. Either start a new paragraph with new thought or remove. 
- Pg. 13 Define "noise" or provide a link a resource explaining it

**Comment by mariaruth** [comment]
solved in re-write
