### ISSUE TITLE
Ch1: Handling data ethically YP edits

### ISSUE THREAD

**Issue by ypowers1** [worldbank/d4di#132]
- [x] Explicate more in introduction that what you mean by ethics is data privacy and not necessarily other ethics of research (like applying intervention to only a random sample or how to ethically interview a woman on sensitive gender-based issues). It took me a while to realize you were only going to address data privacy in this chapter, so need to make that clear.

- [x] Rephrase (confusing how adopting something then becomes a measure of performance): "Their adoption is an objective measure of to judge a research product's performance in both"

- [x] Rephrase first part of sentence (not sure what clause in commas has to two with rest of sentence; seems like separate ideas): "Without these transparent measures of credibility, reputation is the primary signal for the quality of evidence, and two failures may occur...."

- [x] Not sure what this section has to do with rest of paragraph on taking credibility, transparency, and replicability seriously: "This approach opens the door to working with the development community...so it is hard for others to verify that it was collected, handled, and analyzed appropriately."

- [x] Explicate more what processes you mean in this sentence (is it how you determined the survey q's, what assumptions you have in your analysis, etc?): "Transparent research will expose not only the code, but all the processes involved in establishing credibility to the public."

- [x] "Registered reports" section is confusing: need to define what registered reports are and the "file-drawer problem". What does "setting up a large portion of research design in advance" mean? 

- [x] Define "pre-analysis plans" and explain what registering them via the databases mentioned will do (make it public from the outset? why is that good?)

- [x] Suggestion: put privacy section first in chapter as you mention it first in introduction so it follows logical flow

**Comment by bbdaniels** [comment]
Let's make doing the glossary work a different issue/task for a mop-up
