### ISSUE TITLE
Ch 2: Planning data work before going to field YP edits

### ISSUE THREAD

**Issue by ypowers1** [worldbank/d4di#133]
- Having not seen iefolder yet, it's not clear to me how this Stata package creates folders on my computer

- Is "master script" the same as "master code"?

- Suggestion: include mention of Stata style guide somewhere in this section, like "refer to the Stata style guide at the bend for style templates...". Also, consider adding a sample fully formatted do file with correct styling.

**Comment by kbjarkefur** [comment]
- iefolder wiki article is linked to
- yes, same thing but only master script should be used in book. Or master do-file if talking about Stata
- good idea, @bbdaniels mention this somewhere
