### ISSUE TITLE
Ch 4: Sampling, randomization, and power YP edits

### ISSUE THREAD

**Issue by ypowers1** [worldbank/d4di#135]
- Confusing phrasing in sentence: "Sampling noise produces some probability of selection of units to measure that will produce significantly wrong estimates, and randomization noise produce some probability of placement of units into treatment arms that does the same." 

- Suggestion: I would put the Reproducibility section last as my first thought after the intro is "how do I randomize and sample?" After learning how to do this, then I can better understand why I need to care about the process of the randomization and sampling as well. 

- In the Sampling section, I didn't understand why you wouldn't update the sampling universe with data from the field. If there are updates to the sampling universe in real life (like someone passed away), why wouldn't you update? 

- Define "improving the balance of the average randomization draw" means in Clustering and Stratification section

**Comment by bbdaniels** [comment]
> Suggestion: I would put the Reproducibility section last as my first thought after the intro is "how do I randomize and sample?" After learning how to do this, then I can better understand why I need to care about the process of the randomization and sampling as well.

I've left it where it is for now as a sub-intro, but open to moving it to the end as well.
