### ISSUE TITLE
grammar error 4th paragraph 'Writing reproducible code in a collaborative environment'

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#141]
We always tell people to “code as if a stranger would read it”, ~~since~~ _from_ tomorrow, that stranger will be you.

**Comment by mariaruth** [comment]
Corrected all typos in develop branch

**Comment by kbjarkefur** [comment]
not a problem at all, but it would have been better to have made these edits to a `CH1-reveiw` branch. We can talk about workflow in the review meeting today.
