### ISSUE TITLE
add blurb on why stata?

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#142]
I think it would be useful to add a couple sentences to state upfront that this book is designed for stata workflows and code (and why). also a note on relevance for non-stata users.

**Comment by mariaruth** [comment]
added a brief note on this in the intro re-write. anyone have a source to cite that stata is the most widely used in microeconomics? would be nice to add but not critical.

**Comment by bbdaniels** [comment]
https://github.com/worldbank/d4di/commit/aab065bb7d0259b21614ce8565f411c36fbebcbc

https://aeadataeditor.github.io/presentation-20191211/#9

**Comment by luizaandrade** [comment]
Moved citation to intro in 6a7ac8f

**Comment by bbdaniels** [comment]
Close
