### ISSUE TITLE
Overall organization: markers for chapters, sections, subsections

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#143]
I think it would be easier to follow the organizational structure within a chapter if there was a distinction between the levels of headers. for example, my understanding of the outline for handling data ethically is:
1. Handling data ethically
1.1. Protecting confidence in development research
1.1.1. Research replicability
1.1.2. Research transparency
1.1.3. Research credibility
1.2. Ensuring privacy and security in research

is that correct? 

i don't think we should number like this necessarily, but just bigger headings for 1.1 and 1.2 here would help (otherwise it seems that all are at the same level, and it's harder to follow the logical structure of the chapter).

**Comment by mariaruth** [comment]
Related, suggest adding chapter numbers to manuscript.

**Comment by kbjarkefur** [comment]
see issue #78 for index

**Comment by kbjarkefur** [comment]
Chapter numbers were added in https://github.com/worldbank/d4di/commit/2d3276869206f35917c166398ed17aef8aee25df

**Comment by kbjarkefur** [comment]
First attempt to make section titles and sub-section titles appear more different: https://github.com/worldbank/d4di/commit/a590a6a156200a48b366bdae8a07f03c978fdf1f

It looks like this (red line = section, blue line = subsection):

![image](https://user-images.githubusercontent.com/15911801/66001838-5a105280-e470-11e9-88e8-fa41a4a2ba1e.png)

**Comment by kbjarkefur** [comment]
Going through old issues I'm assigned to. I think this is all solved. Chapter numbers are added, there is an index `\index{}`, and the section and sub-section titles are differentiated. I think this can be closed, but since you opened this @mariaruth , I will let you close it if you agree
