### ISSUE TITLE
Ch1: Distinguish between reproducibility and replicability

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#145]
Remove parenthetical that we use them interchangeably and clarify consistently in the text.

**Comment by mariaruth** [comment]
From our blog: "“Reproducibility” and “replicability” are often confused (case in point: a ‘push-button replication’ is in fact a check for computational reproducibility). Prof. Lorena Barba, one of the authors of a 2019 report by the National Academies of Science, Engineering and Medicine, offered the following definitions. Reproducibility means ‘computational’ reproducibility: can you obtain consistent computational results using the exact same input data, computational steps, methods, code, and conditions of analysis? Replicability means obtaining consistent results across separate studies aimed at answering the same scientific question, each of which has obtained its own data."

**Comment by kbjarkefur** [comment]
👍

**Comment by mariaruth** [comment]
Re-opening. I disagree with the line that "We use "reproducible" and "replicable" interchangeably in this book, though there is much discussion about the use and definition of these concepts." I revised in 77c65c88ed6f5444e578c7d90bff088385c0ccaa
