### ISSUE TITLE
CH 5: Ensuring privacy and security in research - add links to tools to de-identify data

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#146]
either in text or on the wiki page

**Comment by mariaruth** [comment]
PII_detection from IPA: https://github.com/PovertyAction/PII_detection
PII_scan from JPAL: https://github.com/J-PAL/PII-Scan
sdcMicro from the World Bank: https://github.com/sdcTools/sdcMicro

**Comment by kbjarkefur** [comment]
Move to chapter 6

**Comment by kbjarkefur** [comment]
Chapter 6 is now chapter 5

**Comment by roshni13khincha** [comment]
IPA Split PII - https://github.com/PovertyAction/split_pii

**Comment by kbjarkefur** [comment]
Related to #151

**Comment by bbdaniels** [comment]
Close

**Comment by luizaandrade** [comment]
This is now in chapter 6. I did not add the IPA packages because they have not been updated in a long time.

**Comment by kbjarkefur** [comment]
I also vote to close, but do not want to close an issue that @mariaruth both created and self-assigned without her having a say first
