### ISSUE TITLE
data: singular or plural?

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#147]
decide so that we all do this consistently throughout!

**Comment by bbdaniels** [comment]
Weirdly the correct answer is to be inconsistent, and change it depending on the use case:

<img width="513" alt="Screen Shot 2019-10-01 at 10 16 56 AM" src="https://user-images.githubusercontent.com/1459122/65970455-9b830c80-e434-11e9-8a10-61838813820f.png">

**Comment by luizaandrade** [comment]
I think we can defer to the DIME style guide for this as in #295 and close this one?

**Comment by bbdaniels** [comment]
Yes, close

**Comment by kbjarkefur** [comment]
Agree. Closing as it is a duplicate of #295 and the other issue includes more
