### ISSUE TITLE
Ch1: typo

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#149]
https://github.com/worldbank/d4di/blob/897ef9d280045199233724b25dac036daf574b1c/chapters/handling-data.tex#L16

> Their adoption is an objective measure of to judge a research product's performance in both

I'm not sure I understand this sentence. Is it meant to be"an objective measure *to* judge"?

**Comment by bbdaniels** [comment]
Remove `of`

**Comment by luizaandrade** [comment]
This sentence has been rephrased.
