### ISSUE TITLE
CH5 : how to improve data security

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/d4di#151]
## Three parts of security handle PII data
Divide this section into three parts. 
* Collecting
* Storing
* Sharing

### Collecting
As the book currently says, data collection software usually solved this for us. SCTO encryption

### Storing and Sharing
* Encrypt the data
* De-identify, and share de-identified data

##### Encryption
Add a section on encryption. We have good guidelines for that. We can link to that from book and just add a short summary

##### De-identification
As suggested in #146 we need to link to the tools we need. but I have a suggestion. 

It is very difficult to determine when a all variables in a data set is de-identified. And the process  of finding the full list of variables that needs to be dropped takes so much time that no one ends up doing it during stressful times like data collection.

However, what is easier than finding all variables needed to be dropped, is to come up with a list of the variables that you need and are safe to keep. This way you only assess PII or not for variables as a need basis during stressful times like data collection. 

Then before publication you are more likely to have time to use some fancy tool to find out what is the minimum list of variables needed to be dropped for the data to be considered de-identified.

This would be a quick way to de-identify the data, so that it can be easily shared without teaching the full team about encryption.

**Comment by kbjarkefur** [comment]
So provide both a safe but quick temporal de-identification strategy, together with fancy tools to do it properly for publication etc. This should improve take up of data privacy best practices.

**Comment by luizaandrade** [comment]
Some more things that I think we should add:
- Avoid the proliferation of copies of identified data
- Not everyone needs access to identified data
- Only information that is *strictly needed* for research should be collected
- This may depend on where you work, but research team members are typically liable for how they handle the data

**Comment by mariaruth** [comment]
Talk about 'publishable' feature of SCTO but not in software-specific language. suggest marking sensitive variables at the time of the questionnaire design. some software allow for a workflow that makes it simple to share 'safe' datasets (e.g. publishable feature of SCTO).

**Comment by kbjarkefur** [comment]
Related to #146

**Comment by luizaandrade** [comment]
From Steven in #159 : A diagram of folder structure and/or workflow (under iefolder) would also be very useful here — including i) what data/folders should be encrypted, ii) how this is set up, iii) when this should be done, iv) how this relates to dropbox access of other research team users.

**Comment by mariaruth** [comment]
There's a substantial amount of overlap between Ch1 and Ch5 on this. let's discuss how to have a clearer division of what is covered where.

**Comment by kbjarkefur** [comment]
done in #366
