### ISSUE TITLE
Tone of text: use of "you"

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#152]
We use sentences such as "the actual analytical processes you used", or "all your code files". I personally prefer making it more generic, but happy to stick to it if that's everyone's preference.

**Comment by luizaandrade** [comment]
We will review this for consistency across the whole book as part of final revision.

**Comment by mariaruth** [comment]
agreed to have a professional editor do an edit at the end of the process to ensure consistent style

**Comment by mariaruth** [comment]
Just to note, along these lines we need to be consistent in whether we use "their code" "their responsibility" or "your code" etc.

**Comment by kbjarkefur** [comment]
I vote for closing as this is a task for a professional editor and not us
