### ISSUE TITLE
Ch1: data ownership

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#156]
- who owns it and what that means for publication
- data sharing agreements with governments
- importance of data sharing agreements
- what the implications are for replication
- data publication options
- no legal / ethical consensus yet

**Comment by mariaruth** [comment]
This is now covered in Chapter 7

**Comment by mariaruth** [comment]
on publishing data i think we should make explicit reference to the Bank's data catalog. and cite their guide on preparing data for public release: https://ihsn.org/quick-reference-guide-for-data-archivists

on licensing the data you publish, the various 'terms of use' options in the Bank data catalog are a good reference. https://microdata.worldbank.org/index.php/terms-of-use

**Comment by bbdaniels** [comment]
Added these three references and notes. I cannot open the last link externally, so if there is something similar that can be external can we find it and put it in Chp 5 as suggested in #351

**Comment by kbjarkefur** [comment]
If this is merged, can we close?

**Comment by luizaandrade** [comment]
I don't think it's merged?

**Comment by kbjarkefur** [comment]
I dont know either, but this issue was referenced in #358 PR that was merged. That is all I knew

**Comment by mariaruth** [comment]
leave this open for now - question is what to do about the intranet links, specifically the data licensing agreement and data use agreement templates. those aren't needed for D4DI, but i think we should put in DIME standards as we want people to use those -- however, should discuss whether or not it makes sense to have a WB only link on a public repo

**Comment by bbdaniels** [comment]
👍🏼
