### ISSUE TITLE
CH5: variable names (Steven's other comments moved to other topics

### ISSUE THREAD

**Issue by bbdaniels** [worldbank/d4di#159]
**iefieldkit**. This is a really useful tool and could perhaps have a paragraph or two explaining its use in this section, currently it’s just mentioned in passing in the first paragraph. I would also move the mention of this to come at the end of the designing CAPI questionnaires section, which could overall benefit from being structured more chronologically.

**Encryption**. I found the discussion of encryption of received primary data somewhat confusing and am still not sure what recommended best practice in practice should be from the text. The text does well in explaining what it is and why it’s important, but then the actual steps to implement this structure was not clear for me. Encryption services are not overly intuitive to use, so this part could benefit from a step-by-step guide on how to use VeraCrypt and it’s integration with Dropbox (as most teams use this). A diagram of folder structure and/or workflow (under iefolder) would also be very useful here — including i) what data/folders should be encrypted, ii) how this is set up, iii) when this should be done, iv) how this relates to dropbox access of other research team users.

**Receiving primary data**: The text references storing a golden master of the data in a secure location, please specify what this means in practice and who should do this and who has access.

**Variable naming**. I have always felt that vars like q410a should never be seen beyond a printable survey instrument and should never be seen in a CTO form. Compact descriptive names accompanied by a codebook should be the way to go. Might be useful to link to this article that I found insightful: https://medium.com/@janschenk/variable-names-in-survey-research-a18429d2d4d8 

**Quality assurance**: The HFC and BC section is well written and I have nothing to add here.

**Piloting:** Perhaps worth including a bit more on the process of piloting and what to look out for? Particularly useful if designing instrument in new setting/sector, and for the purposes of the guide a discussion of the data pilot would be really useful. Though, as most of this is described in the linked wiki page, it might not be essential for here?

**Comment by mariaruth** [comment]
address iefieldkit as part of #256 
address encryption as part of #151 
address piloting as part of #266

**Comment by kbjarkefur** [comment]
Regarding variable names. Describe and discuss the pros and cons with both methods.

Regardless of which method you do, there should be a system to unambiguously tie a variable in the data to the question in the questionnaire without detective work
