### ISSUE TITLE
Ch 2: link to example data map

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#165]
https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/chapters/planning-data-work.tex#L10

**Comment by bbdaniels** [comment]
Vote to close and not do this, we de-bolded the word to make it a general, not specific term

**Comment by kbjarkefur** [comment]
I agree that we can close it as I do not think we have a good comprehensive template, although that would be something useful for the future, but it will not be done in time for the first version of this book, so therefore close.
