### ISSUE TITLE
Overall: update wiki links

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#166]
the "/wiki/" is not needed. For example, instead of dimewiki.worldbank.org/wiki/iefolder, just use dimewiki.worldbank.org/iefolder. 

Both links work. It is true that if you go to the page and then copy the URL you get the extra /wiki/ bit. However, the url without it looks cleaner for the text.

**Comment by bbdaniels** [comment]
This is good. This can be done with a single find-and-replace. Can we also check if they are case-sensitive etc? There are some ugly links with various special characters as well that I would love to update if that doesn't break anything.... ie if there is auto-forwarding on the wiki?

**Comment by kbjarkefur** [comment]
I found some weird case behavior. The link as the wiki generates look like this:

> https://dimewiki.worldbank.org/Encryption#Symmetric_Encryption

Where the subdoman and domain `dimewiki.worldbank.org` are lower case by default and not case sensitive. the path that is the page name `Encryption` is capitalized by default but it is not case sensitive. **_However_**, the fragment which is the section of the page `Symmetric_Encryption` is case sensitive. If you screw up the case in the fragment the URL still works but you get to the top of the page.

**Comment by bbdaniels** [comment]
In general I think they should be lowercased then for the page names. I don't think we use too many direct section links? I tried to avoid that.

**Comment by kbjarkefur** [comment]
I did link to specific section a fair bit for encryption. As I want to link to, for example, symmetric encryption and asymmetric encryption specifically. Also with encryption in transit and at rest.

**Comment by kbjarkefur** [comment]
`/wiki/` removed in dc91a4d50a3dece209436b0933fd2cd58f6deb76

Some more link hygiene done in 6429cb0827cdb3cdf2ec0837b28c69a9b19b6889

I tested capitalization more in the wiki links and it was more complex than I though above. Seems like only the first letter is case sensitive.

* https://dimewiki.worldbank.org/dataWork_Folder works and redirect to https://dimewiki.worldbank.org/wiki/DataWork_Folder
* https://dimewiki.worldbank.org/Datawork_Folder and https://dimewiki.worldbank.org/DataWork_folder does not work.

So @luizaandrade , @bbdaniels and I decided that all links should be as they default on dimewiki. Apart from `/wiki/` that is removed and apart from page names that are single technical words that are names spelled with lower case, like https://dimewiki.worldbank.org/iebaltab

This issue can now be closed
