### ISSUE TITLE
Ch2: Planning data work before going to the field

### ISSUE THREAD

**Issue by morevba** [worldbank/d4di#167]
Below are my feedback after reviewing the chapter. I would like to say that I approached this chapter as an RA starting out in Stata or as someone who enrolls in the Field Coordinator training Stata track 1. 

Feedback:
1. On page 22, midway through the page, the paragraph says "mostly use only, A-Z, dash, and underscore. You should always use forward slashes (/)." 
I think it would be great to include the symbols for dash (-) and underscore (_) in the descriptive as to some people starting out in Stata may have no idea what symbols those words respond to. 

2. On page 23, at the end of the Folder Management section, it says "The code below shows how folder structure is reflected in a master do-file." 
The code is actually on page 25, not below the paragraph and this may actually be a result of how the book was printed out.

3. The Output management section mentions Git a few times but fails to mention the fact that the iefolder command creates an Output and Documentation folder. Ideally, this is where the outputs for the projects should be stored. Anything that is created as a result of running a do-file that is not a dataset should be stored in either of these folders, that's the main reason why they were created. Thus it would be easier for a team to know where the outputs are located. I think mentioning the iefolder creates an Output and Documentation folder in this section would be great especially if the person ends up using iefolder they will know where to store their outputs and the file paths are mentioned in the project_master_dofile. 

4. I really like the preparing for collaboration and replication section at the end but it seems out of place especially the mention of replication. I understand the collaboration part because this section handles setting up the right data folder and annotating the do-files so everyone can interpret your coding. I felt that this section should be added to the Publishing Collaborative Research chapter but it could be out of the place there.

Overall, this section was great. I really liked this chapter and the main points were really drilled in and repeated so the reader knew the importance of iefolder and always annotating your do-files and naming files appropriately.

**Comment by kbjarkefur** [comment]
We decided to not count introduction as chapter 1, so this is not counted as chapter 2, therefore the new chapter number is 2.
