### ISSUE TITLE
Ch 2: revisit "setting up your computer" section

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#174]
This section alternates super high-level content and super detailed software recommendations. Maybe we should start by just listing what are important things to address here? Here are a few things that I think should be included:
- Password protection
- Hard-drive encryption
- Back-ups
- Types of data and computer processing power and storage space

Naming conventions and file paths are very relevant and often overlooked topics, but should probably be in a separate section.

**Comment by mariaruth** [comment]
Also - are the software we mention here all things we recommend? for example i've never heard of backblaze. maybe specific software references could go into side notes as examples, whereas the main content is higher-level.

**Comment by luizaandrade** [comment]
See #185
