### ISSUE TITLE
Ch 2: discuss why coding is important

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#178]
This is a good point to explain that we will assume everyone is writing code, and explain why. Discuss replicability, automation (how many times you'll do something vs how much time to spend on doing it replicably), transparency, etc.

**Comment by kbjarkefur** [comment]
Write a short section on why we need to learn to code in beginning of _Code Management_ section

**Comment by kbjarkefur** [comment]
Not sure why I am assigned to this issue. I self-assigned so I am only asking you to help me ask myself. But I did go through this chapter looking for the solution to this issue.

Is this `ok2go`? I am assigned to this and I do not see a direct explanation to "Why we code?"

I was looking for something in the line of "your code is a recipe", "your code is just as much an output of your research as table and graphs" or "we should not trust research where we are not shown the recipe on how it was made".

Let me know if there is anything that I have missed.

**Comment by luizaandrade** [comment]
No, I don't think this is ok2go. There's very good discussion on how to organize and manage code, but the step of why to write code is still missing.

**Comment by bbdaniels** [comment]
@luizaandrade Can this be closed?

**Comment by luizaandrade** [comment]
Yes, this is great.
