### ISSUE TITLE
Ch2 : 1-2-3 only for master copy of the data

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/d4di#183]
https://github.com/worldbank/d4di/blob/f3b49341f1a2c82b88c6d9d4f02d0c8ff8542b89/chapters/planning-data-work.tex#L60-L64

I do not think this has to apply to all copies of the data on everyone's computer. This is only for the safe keeping of the data in case of someone accidentally deletes it.

**Comment by mariaruth** [comment]
Also i think it would be helpful to be more specific  on how to implement this (probably in a wiki page rather than here). i'm not actually sure how i would implement this on my computer.
