### ISSUE TITLE
ch2 : mention security concerns with sync software first time we mention it

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/d4di#186]
https://github.com/worldbank/d4di/blob/3e97cf38e041784c410e9cde91181277e7efec04/chapters/planning-data-work.tex#L94

We should have some text here about sync software has security weaknesses. We can reference chapter where it is explained in detail for more datails

**Comment by kbjarkefur** [comment]
@bbdaniels , in 4fbc425 we are saying that we will address those security concerns later. Are we doing that?

**Comment by luizaandrade** [comment]
👍

**Comment by bbdaniels** [comment]
Added explicitly to the security section in 66cec1e1d7344bdc44b3d18f455b815f6c8b0c3c

**Comment by kbjarkefur** [comment]
Great. Vote to close
