### ISSUE TITLE
ch2 : DIME template not for everyone

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/d4di#189]
Add section on that DIME folder template is not for every project

**Comment by kbjarkefur** [comment]
This paragraph drafted in 3e1c38521e8ffc27684117a309c932d8a9c5954f

**Comment by kbjarkefur** [comment]
fix `Analytics'` - bad @kbjarkefur

**Comment by kbjarkefur** [comment]
I fixed the stupid typos. @bbdaniels , feel free to close or edit and close as you think is best.

**Comment by bbdaniels** [comment]
Alternatively in cases like this, to avoid issues: "according to the DIME Analytics template" etc.? @mariaruth
