### ISSUE TITLE
script vs. do-file

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#191]
We currently use script and .do file interchangeably. we should at least explain early on that we do so. or, i think better, we are consistent and only use one. since we are providing examples of stata code i think sticking to .do file is better, but let's discuss. 

This applies to Ch 2 but also to the rest of the book.

**Comment by mariaruth** [comment]
Do a comprehensive check of this as part of final review

**Comment by mariaruth** [comment]
related, make sure that we use "do-file" instead of ".do file" or "do file"

**Comment by luizaandrade** [comment]
I have marked all occurrences of the expression. They are mostly "do-file" already. Will wait for everything to be merged to develop to fix it.
