### ISSUE TITLE
Stata vs. R

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#193]
Need to clarify how much we include R - sometimes there are examples of analogous syntax / code. But not consistently, and all the code examples are stata. perhaps we say at the beginning that this is designed for stata users but we'll add in R references as useful?

**Comment by kbjarkefur** [comment]
Put this some text about why we use Stata (resources are more scarce for Stata) since several software can be used, but everyone should research what software to use based on GIS, big data etc.

**Comment by mariaruth** [comment]
Add a clear introductory statement that we will add r references as much as possible (put this in a section where we also explain that we use stata primarily)

**Comment by bbdaniels** [comment]
Vote to close

**Comment by luizaandrade** [comment]
I will add it with the explanation of why we use Stata.

**Comment by mariaruth** [comment]
Closing, this is now well covered (#393)
