### ISSUE TITLE
Ch 2: folder structure in github and dropbox

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#195]
The division between github folder / synced folder should be explained more clearly. or, better, refer to a wiki page with detailed instructions or a training. it may be the case that we need to come up with more definitive guidance here.

**Comment by kbjarkefur** [comment]
@kbjarkefur , will come back to this once more resources are developed

**Comment by mariaruth** [comment]
I think this is now clear enough in the text, but leaving it open for wiki development

**Comment by mariaruth** [comment]
this is duplicate with #330 . closing this one.
