### ISSUE TITLE
Ch2: who creates folder structure

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#201]
if using standardized structure like iefolder this is a moot point. but otherwise I think it's preferable for PI to set up overall structure they're comfortable with, rather than having the RA do it. 
https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/chapters/planning-data-work.tex#L106

**Comment by luizaandrade** [comment]
Also mentioned by Aram in #84:

> Since RA and FC come into a project when generally a shared folder already exists, I think that it is worthy at some point to insist on the fact that the folder creators (TTLs and external PI most of the time), start with a clear structure upfront so that when assistants take over, not many restructuring would be needed. Having a continuing education session targeted to TTL on the matter may be useful.
