### ISSUE TITLE
Ch 7: Better case for bibliography

### ISSUE THREAD

**Issue by escandethomas** [worldbank/d4di#210]
https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/chapters/publication.tex#L82

I think we can make a stronger case here for why Latex is better at handling bibliography, underlining how easy it is to change citation/ bibliography style if for instance you want to publish in different journals with different requirements. 

Also, something I was thinking about: do you think that DIME analytics could create and keep up to date a library of the different .bst for all the citing / bibliography styles for the main eco journals? All in the same location, easy to find, I think that would be a great public good as I did struggle a lot last time I had to do a bibliography and ended up writing my own .bst file that I am happy to share!

**Comment by bbdaniels** [comment]
https://github.com/citation-style-language/styles
