### ISSUE TITLE
Ch 7: Develop overelaf characteristics

### ISSUE THREAD

**Issue by escandethomas** [worldbank/d4di#212]
https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/chapters/publication.tex#L56

It would be nice to add that overleaf allows collaborative editing and commenting similar to google doc and with the paid version, you can also have track changes and synchronization with Dropbox, which is one of the limitation you are quoting here. .

Overleaf also has a lot of easy to read documentation that Latex does not necessarily have.

**Comment by kbjarkefur** [comment]
Lets do this, but we have decided that we will make the software specific section overleaf shorter as we do not want to get stuck with software specific recommendation that might become outdated

**Comment by bbdaniels** [comment]
Made this a whole subsection actually but perhaps it can be generalized away from Overleaf. To-do in review
