### ISSUE TITLE
Ch 7: General Comments "Publishing Collaborative Research"

### ISSUE THREAD

**Issue by escandethomas** [worldbank/d4di#213]
Just wanted to give some more general comments after the few detailed ones I put in the text. 

- On the general organisation, I would have first a paragraph on best practice : doing everything in Latex (though it is debatable now, see this paper https://journals.plos.org/plosone/article?id=10.1371%2Fjournal.pone.0115069&fbclid=IwAR2Vq6LNPH5BF4Xti7xlNb0As4LASPZ5Sb0AcmXUoiJwPOj3J7Dk0zN4ukQ :) ) and explain why it is best to use latex or overleaf: bibliography, dynamic document, synchronisation with dropbox, version control, formatting, no crashing, ... Tables can be done directly in the stata/r code using markdown, and then inserted as separate objects in the latex code.
 If that is not possible, as it can be often difficult to have all the authors use Latex or overleaf if they are not used to it for collaborative work,a second best option could be using latex / overleaf for the tables / figures (easier to format and to ensure reproducibility) and word to write the text, comment, tracking changes, and in a final step use the tools cited below to transfer the text in latex and add the bibliography.  

- Other tools: 
     There are a lot of websites that translate directly word / excel in latex code. 
     This app (https://mathpix.com/) can be really useful to get the latex code of equations, it even works for handwritten equations, it is really impressive. 

Otherwise, I think constraints are well explained, the case for adoption could be stronger by listing more of the advantages of latex/ overleaf over word (notably no risk of word crashing or of the format of the word document changing). Maybe also useful to mention that overleaf and latex have a lot of online documentation and maybe a link to some guide/lesson to start using latex or overleaf. 

But in summary, I am convinced!

**Comment by kbjarkefur** [comment]
merged with #283
