### ISSUE TITLE
Ch3: Overall content / structure

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#214]
The intro states:
> "This section will present a very brief overview of the most common methods that are used, so that you can have an understanding of how to construct appropriate counterfactuals, data structure, and the corresponding code tools as you are setting up your data structure".

I think that's exactly the right premise for this chapter but it's not actually what i see in the subsequent sections. There's nice summary discussion of methods / counterfactuals, but very little on what are the implications for data structure or corresponding code tools. I think of the objective of the chapter as - i'm an RA, i know from the concept note what the design of the study i'm working on is, but i don't:
* a) really understand the method [that's addressed as the chapter is], 
* b) know what that means for how i need to set up the data for analysis and 
* c) what code tools i should use in doing when it comes time to do the actual analysis. 

the current content covers **a)** well, doesn't cover **b)** at all, and kind of covers **c)** but only in side notes, i suggest making this explicit in the text. i didn't even notice the references to ieddtab and iematch until the third read through!

**Comment by kbjarkefur** [comment]
I formatted the comment above, but the content is the same

**Comment by kbjarkefur** [comment]
the same comment as @mariaruth is bringing up here was my main comment after my read-through. This was the thinking I had done. 

Similarly to what Maria said, I think we need to clearly define what this chapter is for. Currently the content is correct and it is well written, but the unclear objective makes it into a lot of good threads that are not tied together. Now it is not clear if this is a RA-focused compliment to an econometric text book or a very thin substitute. It should obviously be the former.

I agree with Maria's three bullet points, but to that I want to add this.

The intro needs to be more on point why we focus on causal design. Now it almost seems like we picked what we happen to know, but I think there is a good case saying *causal is important for impact.

Then I think the first section should discuss all themes common in causal designs. Currently it is only treatment and control. I think that could be expanded to include balance, and discussions on how time effects, short comings in countrerfactuals. 

Then there is a section that as briefly, or even more brief, as the IV and Matching section discuss how they are econometerically different, but then the focus for each model should be Maria's point *b)*.

**Comment by kbjarkefur** [comment]
**MVO**:

* Provide a good intuition to each design (almost there, just simplify some word choices)
* What are the implication for the data when using this model
* What are good tools if any

**Comment by kbjarkefur** [comment]
@kbjarkefur , will help point out where simplification is needed for i)
