### ISSUE TITLE
Ch3: clarify cross sectional time dimension

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#215]
Explain time dimension more clearly, i.e. that in a repeated cross section the sample is re-drawn each round (so the same individuals are not necessarily revisited and an individual-level panel would not be appropriate, even if there is overlap in the samples)
https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/chapters/research-design.tex#L120

**Comment by bbdaniels** [comment]
Removed.
