### ISSUE TITLE
Ch3: Balance checks in cross section?

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#216]
Maybe this is a typo, and should be cannot? I assume so based on the second half of the sentence. 
https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/chapters/research-design.tex#L126

**Comment by kbjarkefur** [comment]
Remove as this is the type of questions we should not get involved in here. This is a typical thing that the PI will decide
