### ISSUE TITLE
Ch3: DiD parallel trends

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#218]
Clarify differences between DiD in experimental and non-experimental setting. I understand with the way this is structured (part of the experimental research designs section) that this is referring to DiD in experimental contexts. But parellel trends is the critical identifying assumption in non-experimental settings. 

https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/chapters/research-design.tex#L153

**Comment by bbdaniels** [comment]
Isn't this because the randomization is assumed to automatically satisfy it? You should still validate parallel trends even if you randomize, right (ie through RI or some such)?
