### ISSUE TITLE
Ch4: Add preview of chapter structure to intro

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#224]
Add a new para to intro (would be paragraph 3),  previewing what the chapter will cover. i think a little more structure on what we are trying to cover would help both write that preview and organize the content. 
Also doing this would help the reader understand why a section on reproducibility comes first when that's not an obvious part of the chapter from the title (e.g. say something like and that first, we discuss critical coding practices to guarantee that sampling, randomization and power calcs are reproducible.)

**Comment by kbjarkefur** [comment]
solved in #225 and #236
