### ISSUE TITLE
Ch4: content and organization

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#225]
I was not totally clear on the objective in this chapter. I think it's how to code sampling, randomization, and power calcs reproducibly, accurately, and efficiently. yes? 
Some of the sections seem less focused on application than explanation. perhaps some of the explanation should be moved to corresponding wiki pages? In general, i found a lot of the explanations to be quite abstract. perhaps having an example that gets re-used throughout the chapter would help.

**Comment by mariaruth** [comment]
I think that typically, randomization happens before sampling (e.g. treatment randomly assigned across 200 villages; then 10 hhs are sampled within each village). now there could be an element of sampling to get to 200 villages (if there is a larger population of villages) - but this is less common. for that reason i would suggest restructuring to Ch4: Randomization, Sampling and Power, and moving the sections around accordingly.

**Comment by kbjarkefur** [comment]
I agree with Maria's points. Especially that it focuses more on abstract concepts than making sure that the readers leaves the chapter with the understanding that a typical RA need.

I think the chapter should be structured in first simple and advanced. Here we are talking about sample noise already in the introduction, and I fear that the target audience for this book will leave reading that intro more confused than before. 

I think sample noise should not be mentioned until the very end of the chapter. We need to gradually build up the readers understanding of the reader. 

I agree with #224 to add an intro. I think these should be the sections.
1. Intro
1.2 The three rules of randomization in *Stata* (I think this section must make clear that these are the rules in Stata). 
2. Simple cases (talk about randomization and sampling being very similat)
2.1 basic randomization - Meaning randimizations into two groups 
2.2 basic sampling - similar to 2.1 (do not use the command `sample`, see issue #229)
3. Clusters
3.1 Clustered randomization - `bys cluster : keep if _n ==1` then simple rand
3.2 Clustered sampling 
4. Multi arm and strata
4.1 Multi arm randomization
4.2 Then strata. 
4.3 Then show `randtreat` for imbalanced strata etc.
5. Advanced topics 
5.1 Sampling noise 
5.2 Randomization noise - randomization inference
5.3 Power calc - min detectable effect 
5.3 Power calc - minimum sample size

Sub sections in section 5 should be shorter, or at least less theoretical. it is no handbook for PIs. This is not where the RA should spend their time. But do not cut out as it is important that they know and have an intuition for.

I can re-write code so it does not use programs. I think that is just complicating things.

**Comment by luizaandrade** [comment]
- I think this chapter is very detailed in comparison with other chapters. This is the only chapter where we get into the details of the code, for example. This could be the model we go for, but I think that is not the purpose of a reference guide. We could link to more detailed content that is stored elsewhere, for example.

**Comment by luizaandrade** [comment]
> 1. Intro (where we tell them that the simple cases are school book cases and that the world is never that simple, so they need to read all of chapter, we only show simple cases for pedagogical reasons.)
- Explain the *intuition* behind the stats concepts.
- Explain that this is crucial to any project, since it's the very starting point and affects everything else
- Explain *why* reproducibility is absolutely essential here
- Explain how "random" numbers are generated by a computer
- Explain that the chapter will focus on the implementation of randomization *in Stata*, and how the random number generation affects it
- Mention the three rules, but probably don't get into details yet

> 2. Simple cases (talk about randomization and sampling being very similar)
>    2.1 basic randomization - Meaning randomization into two groups
>    2.2 basic sampling - similar to 2.1 (do not use the command `sample`, see issue #229)
> 3. Clusters
>    3.1 Clustered randomization - `bys cluster : keep if _n ==1` then simple rand
>    3.2 Clustered sampling
> 4. Multi arm and strata
>    4.1 Multi arm randomization
>    4.2 Then strata.
>    4.3 Then show `randtreat` for imbalanced strata etc.
> 5. Advanced topics
>    5.1 Sampling noise
>    5.2 Randomization noise - randomization inference
>    5.3 Power calc - min detectable effect
>    5.3 Power calc - minimum sample size
> 
> Sub sections in section 5 should be shorter, or at least less theoretical. it is no handbook for PIs. This is not where the RA should spend their time. But do not cut out as it is important that they know and have an intuition for.
> 
> I can re-write code so it does not use programs. I think that is just complicating things.

**Comment by kbjarkefur** [comment]
- No appendix
- Move code examples of the three rules of randomization to wiki and link there

**Comment by mariaruth** [comment]
@bbdaniels i expect all these issues are addressed with the rewrite but i will let you confirm and close
