### ISSUE TITLE
Stata code snippets

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#226]
This issue came up as I read Ch 4, but applies to all chapters with code snippets. A few practices all code snippets should follow: 

- [x] all commands written out in full (e.g. capture instead of cap, generate instead of gen)
- [x] standalone (load any data that is required to run, those datasets should either be system datasets or on our github) -- and all .do files should start by loading data so that readers can try it out without having to load their own data first
- [x] have extensive comments, explaining each and every step (even more than typical code)
- [x] comments should preview what is expected to be seen for code meant to illustrate a certain point (i.e. tab sample at the end of simple-sample.do -- this will show us that indeed 20% of the population is sampled).

**Comment by mariaruth** [comment]
Related, in-text code fragments are sometimes hard to distinguish from actual text (in printed pdf format). i wonder if it might be useful to always have a linebreak with a code snippet? not necessarily when it's one word but when there's a code phrase (e.g. isid [id_variable], sort)

**Comment by kbjarkefur** [comment]
Regarding your first point, in the Stata appendix (page 79 in the book) we are saying that we are allowing some abbreviation if they are very widely used. We can discuss this further. See table from book:

![image](https://user-images.githubusercontent.com/15911801/67246618-edfc8b00-f42c-11e9-944f-4173d2dca200.png)

I agree with your other comments.

**Comment by mariaruth** [comment]
Ah, i hadn't realized this is in the appendix. i think that's fine, but we should clarify early on in the book that we're doing that and make sure people know to reference it.

**Comment by luizaandrade** [comment]
👍
