### ISSUE TITLE
Code doesn't run

### ISSUE THREAD

**Issue by ankritisingh** [worldbank/d4di#228]
https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/code/code.do#L12

svmat results, n(col)
_cons invalid varname
r(198);

**Comment by kbjarkefur** [comment]
Thanks for letting us know @ankritisingh ! Did you get an error on that row with `svmat results , n(col) '? I also get an error but on an earlier line. I get an error on line 8.

https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/code/code.do#L7-L12

The error comes from the transposing sign `'` is mistaken for an un-matched end to a local. The mistake was introduced here: https://github.com/worldbank/d4di/commit/de04e3d89cd4fcf7935a95dabe4b2048998adfc4

If you do not mind, can you let me know if you get any other error then this:

```stata
. * Transpose and store the output
. matrix results = `r(table)'
matrix not found
r(111);
```

Thanks!

**Comment by kbjarkefur** [comment]
@luizaandrade , read my message and you will see why I am assigning you :stuck_out_tongue_winking_eye:
