### ISSUE TITLE
Ch4: what makes good seed

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#230]
Add a sentence on what makes a good seed (i.e. don't follow a pattern, don't use a 1 digit number, don't always use the same number, etc) - this to justify why best practice is just to choose a random seed as per the instructions here. 
https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/chapters/sampling-randomization-power.tex#L64

**Comment by luizaandrade** [comment]
I think this is a necessary discussion, but...
- Not sure it should come so early in the chapter. It's fine to mention it here, but I think we should have a separate section to discuss the three rules (I mentioned it in #225)
- Also not sure why use a bitly link that masks the source of the lottery.

**Comment by bbdaniels** [comment]
The underlying link is a real pain: `https://www.random.org/integers/?num=1&min=100000&max=999999&col=5&base=10&format=html&rnd=new`. If there's a more direct shortcut I'd also prefer it but this is what I got

**Comment by kbjarkefur** [comment]
There doesn't seem to be default values in the GET request, so the only way I was able to shorten that was to do `https://www.random.org/integers/?num=1&min=100000&max=999999&col=5&base=10&format=html`
