### ISSUE TITLE
Ch4: what is a LOCKED copy?

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#231]
https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/chapters/sampling-randomization-power.tex#L58

**Comment by luizaandrade** [comment]
I was about to add the same comment, lol

**Comment by bbdaniels** [comment]
This is a good comment. How do you ensure the data does not later change? I have seen the practice of making an explicit "randomization" or "locked" copy of the data when the draw is done. But realized this is something we don't have a recommended practice for
