### ISSUE TITLE
Ch4: sorting

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#233]
The second two sentences read like a description of seeding not sorting? Perhaps I'm misunderstanding. But setting the start point makes me think of seeding. Whereas i think of sorting as making sure that the dataset is consistently ordered. 

> Most random outcomes have as their basis an algorithmic sequence of pseudorandom numbers. This means that if the start point is set, the full sequence of numbers will not change.
 
https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/chapters/sampling-randomization-power.tex#L56

**Comment by kbjarkefur** [comment]
Seems related to #125
