### ISSUE TITLE
Ch4: Provide answers to questions

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#234]
These questions are great. but we should provide answers somehow - could be as a footnote or a reference in the back if we want to more consistently ask questions about the code samples (I think this is a nice approach).
https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/chapters/sampling-randomization-power.tex#L77

**Comment by mariaruth** [comment]
Related - it would be useful to add some discussion of output (for example the graph produced at the end of minimum-sample-size.do). this could be in comments in the .do, or possibly a brief paragraph after.

**Comment by bbdaniels** [comment]
Removed -- need to do the code annotation separately after rewriting
