### ISSUE TITLE
Ch4: Reproducibility in statistical programming is absolutely essential

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#238]
I absolutely agree. But we should either discuss why, or reference to a chapter where we did that, or just remove the statement.

https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/chapters/sampling-randomization-power.tex#L33

**Comment by kbjarkefur** [comment]
I think the point that reproducability is important has already been made. 

I think the point that we need to make here in this chapter is that even randomization can be made possible to reproduce. In the FC training track 1 people often go "Woooow" when I shown them that that is possible.
