### ISSUE TITLE
Ch4: randomization-program-1.do

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#240]
start by calling in data so that this is self-standing

**Comment by bbdaniels** [comment]
Data should not be used inside the program context. The idea is that `randomization-program-1.do` and `randomization-program-2.do` (where the data is used) would make up part of the same dofile? maybe that can be clearer or they should be explicitly combined and referenced by line

**Comment by mariaruth** [comment]
Ah, if they're meant to go together that makes sense - otherwise was
suggesting to pull in data so people can see how the program works (but i
see now that is happening in program 2, i didn't think to connect the two).
so should make that more explicit (or just combine to one and reference by
lines).
