### ISSUE TITLE
Ch4: use programs in code snippets

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#245]
I can re-write code so it does not use programs. I think that is just complicating things.

_Originally posted by @kbjarkefur in https://github.com/worldbank/d4di/issues/225#issuecomment-544780222_

**Comment by mariaruth** [comment]
Let's discuss using programs in code snippets. If we want to keep as is, should add a section on motivation for doing so, and explanation for syntax of creating program (this would be better in linked wiki page)

**Comment by kbjarkefur** [comment]
- remove program from any code before the advance topics section

**Comment by kbjarkefur** [comment]
Any such file is removed in e2cc7015db51fd841fa41a13afd77cc155d6db9e, and the `randtreat` example is written without programs in dfdd4f480daa937aa28c92dd7fc0b5caf3da93ae
