### ISSUE TITLE
Ch4: how to write randomization code

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#252]
- [x] We will use the code from Stata track 1 in the text. @kbjarkefur will add that.
- [ ] On the wiki, we will:
   - Have snippets for different ways this can be done
   - Discuss the pros and cons of each way

**Comment by kbjarkefur** [comment]
Code on randomization is added in e7193932ad4f49e28557209c27f3705e765e9e09 and in 35a6d3201b9231ee55ab95a14b10212910369460

I have not written any of the wiki articles for more advance approaches

**Comment by kbjarkefur** [comment]
Included in #366
