### ISSUE TITLE
CH5 : Most data collected

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/d4di#254]
https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/chapters/data-collection.tex#L4-L5

Most data collected these days is not CAPI, most data is collected by twitter, google etc. Maybe most _primary data for research_ is collected using CAPI.

**Comment by mariaruth** [comment]
Change to "most **primary** data collection is now done using digital data entry ..."
