### ISSUE TITLE
Ch5: scope

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#255]
let's discuss what our intention is with this chapter. primary data collection is clearly a huge topic. i am not sure about the right balance between breadth and depth here. i think we probably want to keep the same data/RA-focus as in the rest of the book - but we should then clarify at the beginning that we are discussing primary data collection in that light. that this is not intended to guide survey design (expect for data implications) or field management etc.

**Comment by mariaruth** [comment]
Related, i suggest adding a new first intro paragraph, and move the CAPI content to the CAPI section. the second paragraph is good but overview of contents doesn't quite align with sections.

**Comment by luizaandrade** [comment]
I agree. I don't think we should go into details about survey design, for example.

**Comment by mariaruth** [comment]
discuss survey design as it relates to analysis. RAs should think about the indicators that will need to be constructed and whether all the necessary variables are in the form. also a good chance to flag the variables that will be high priority for data quality checks. pre-analysis plan is the most structured way to do this, even if teams don't write a pap this is an important conversation to point to. this blog has good details: https://blogs.worldbank.org/impactevaluations/a-pre-analysis-plan-checklist

**Comment by mariaruth** [comment]
Addressed in chapter edits in #310
