### ISSUE TITLE
Ch5: iefieldkit

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#256]
suggest we feature iefieldkit more

**Comment by kbjarkefur** [comment]
Also brought up in #159 , with more details

**Comment by luizaandrade** [comment]
From Yifan in #136: it's not clear what "form-checking routines means"

**Comment by luizaandrade** [comment]
Also, from Steven: "This is a really useful tool and could perhaps have a paragraph or two explaining its use in this section, currently it’s just mentioned in passing in the first paragraph. I would also move the mention of this to come at the end of the designing CAPI questionnaires section, which could overall benefit from being structured more chronologically."

**Comment by mariaruth** [comment]
Is content on iefieldkit in chapter edits in #310 sufficient?
