### ISSUE TITLE
Ch3: Synthetic control

### ISSUE THREAD

**Issue by bbdaniels** [worldbank/d4di#262]
https://economics.mit.edu/files/17847

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RadhikaKaul** [comment]
I wanted to suggest this in the last meeting but forgot. Can we use the 'Proposition 99' paper by Abadie et al. (https://www.nber.org/papers/w12831.pdf) as suggested reading for synthetic controls. I really thought it was quite intuitive and would be helpful for RAs to actually understand the reason why using synthetic controls is essential (in the context of an actual policy intervention).
