### ISSUE TITLE
Ch 5 : coded responses - equally much about quality as speed

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/d4di#263]
https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/chapters/data-collection.tex#L83-L85

I always saw coded answers to have to do with reducing ambiguity in answers and removing the subjective component for the research team to interpret the answer which is a data quality aspect.

As in the question "_What do you like about the current policy?_", how would you rank these open ended answers: "_It is great_", "_It is so much better than the last policy_", "_I think that this other policy is even better_".

**Comment by mariaruth** [comment]
Addressed in chapter edits in #310
