### ISSUE TITLE
Generalize specific software recommendations

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#265]
Try not to recommend specific software, but rather recommend principles and then point to current software solutions.

**Comment by mariaruth** [comment]
>I hope that this book will help you do social research using the digital systems that exist today and the digital systems that will be created in the future. I started doing this kind of research in 2003, and since then I’ve seen a lot of changes. I remember that when I was in graduate school, people were very excited about using MySpace for social research. And, when I taught my first class on what I then called “web-based social research,” people were very excited about virtual worlds such as SecondLife. I’m sure that in the future much of what people are talking about today will seem silly. The trick to staying relevant in the face of this rapid change is abstraction. Therefore, this is not going to be a book that teaches you exactly how to use the Twitter API; instead, it is going to be a book that teaches you how to learn from “digital exhaust” (Chapter 2). This is not going to be a book that gives you step-by-step instructions for running experiments on Amazon Mechanical Turk; instead, it is going to teach you how to design and interpret experiments that rely on digital age infrastructure (Chapter 4).

**Comment by bbdaniels** [comment]
I think this is OK to close at the current stage unless we have specific feedback remaining.

**Comment by luizaandrade** [comment]
I will keep this in mind as I read evertyhing again

**Comment by mariaruth** [comment]
Reviewed with this in mind - i think we strike the right balance now.
