### ISSUE TITLE
Ch6: Content and organization

### ISSUE THREAD

**Issue by bbdaniels** [worldbank/d4di#269]
My vision for this chapter is to reorganize and expand on the headings that are in place as follows:

1. Organizing and cleaning primary data

This should cover the process of receiving data (whatever is not covered in the previous chapter); backing up an encrypted copy of rawr survey files, creating a de-identified dataset, and doing all cleaning, up through the point of having a "clean" dataset whose contents exactly match the survey questions (with original variable naming and ordering). This dataset should essentially be a publishable version.

2. Constructing analysis datasets

This should cover the process of creating "analytical" or "constructed" datasets from the clean data. This section should emphasize that each analytical product -- such as a paper -- should begin fresh from the (fixed) clean data, so that none of the analyses are interdependent on choices about variable construction etc. This can either be through setting up a separate directory for each project/paper (such as the "merged baseline-endline" analysis etc) or a separate dataset for each. This is the time to conduct subsetting, merging, appending, etc. and to name derivative values functionally.

3. Analyzing data and producing outputs

This should cover the organization of analysis code, as well as common technologies for creating and outputting tables and figures. Should emphasize that "interactive" code should not remain in analytical files. Should cover choice of plaintext and binary outputs. Should suggest "content" and "formatting" in separate steps. (Can crib heavily from https://github.com/bbdaniels/stata-tables)

**Comment by luizaandrade** [comment]
My vision would be something like this:

## Overview
- Point here is to organize code, folders and data sets in a manner that the project is (i) easy to follow, (ii) well documented, and (iii) intuitive
- This involves, in my view, the following key elements:
   - Master do files
   - Master data sets
   - Folder structure
   - Task break down (cleaning, construction analysis)
- The task breakdown is more pedagogical than practical: you typically do things at the same time, you only write them separately so you know how to retrace your steps when needed
- Two things to keep in mind: unit of obs and unit of analysis. The unit of observation is how you collect the data. The unit of analysis is how you want it to be at the end of the process. These steps take you there.

## Data management
- `iefolder` is focused on primary data, but the point is to have a folder structure in mind that fits the project
- Each source of data, that will be processed separately, gets a folder
- There's also a folder for the appended ("Panel") version and for each unit of observation ("Master data set")
- Clearly named so you can see how the data and code structure relate to one another
- The master do-file connects code and folder structure

## Data cleaning
- Receive data -> encrypted folder
- Identified data: typically only used during data collection. If needed for analysis, keep analysis data set encrypted
- Initial de-identification
- The point of data cleaning is to document the data set so it is as self-standing as possible
- No changes from the raw data, should always connect clearly to the questionnaire
- Tasks listed in the chapter already (maybe discuss a little more?)
- `iecodebook`
- `ieduplicates`
- Result is typically one clean data set per unit of observation

## Indicator construction
- Construction is done separately from analysis to make sure there is consistency in the indicators used for analysis
- Turn data into the unit of analysis
- Common sources of error: merge, reshape, collapse
- Create final data sets, that also need to be carefully documented

## Data analysis
- (this is quite good as is)
- Exploratory analysis vs. final analysis
- Exploratory analysis: probably in a markdown document?
- Final analysis: load data set, select sample, run regression
- As simple as possible, so people can focus on the metrics, not on the 5879 intermediate matrices you are creating
- Make decisions very explicit in the code (clustering, sampling, controls, etc)
- Use globals to make sure specifications are consistent throughout the analysis

**Comment by luizaandrade** [comment]
Also, should mention code review somewhere

**Comment by mariaruth** [comment]
Ben's original point here relates to new issue #390
