### ISSUE TITLE
Ch6: outputs on git vs dropbox

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#274]
We also discussed this during the training, and both options were floated as possibility. discuss whether we do have a clear recommendation here.

**Comment by bbdaniels** [comment]
I think we should keep with the rewrite of the earlier chapter that outputs/processes can live on any type of sharing service as long as the procedures for privacy, access, and version control are clear. I think the key question to address is how to handle the situation when outputs are "many-to-many"; ie there may be multiple outputs from a baseline, multiple outputs from an endline, and multiple outputs from the combination of baseline and endline. I personally handle this by getting each of the "rounds" to a "clean" phase, and then starting a separate directory for analytical work. I think this is the biggest departure from what we have routinized now and we should think about it (ie, more clearly separating data collection and cleaning and data analysis).

**Comment by luizaandrade** [comment]
I am now also doing that, actually: the cleaning is round-specific, as the instruments may vary. Then I create the panel and to construction there (in #269 I suggest round folders, master data folders and a "panel" folder). But I don't think this is a git vs. dropbox issue?

**Comment by luizaandrade** [comment]
On git vs. dropbox, my take is that anything we want to have version control for, including tables, should be on git.

**Comment by kbjarkefur** [comment]
- everything that can be version controlled - including tables - should be version controlled
  - requires git to access tables or someone with access to git get them for you
- each source of data should be cleaned separately they should have their own folder, and if they are analyzed together that should be done together
