### ISSUE TITLE
Is this a good place for more material on coding?

### ISSUE THREAD

**Issue by bbdaniels** [worldbank/d4di#277]
Such as the following:

https://thepoliticalmethodologist.com/2016/06/06/embrace-your-fallibility-thoughts-on-code-integrity/

https://github.com/nickeubank/DefensiveProgramming/blob/master/Eubank_DefensiveProgramming.pdf

**Comment by bbdaniels** [comment]
"data science" material: https://github.com/uo-ec607/lectures

**Comment by bbdaniels** [comment]
https://www.dropbox.com/s/wqefknwfb91kop8/Coding_For_Econs_20190221.pdf?dl=0

**Comment by mariaruth** [comment]
@bbdaniels - i understand this question to be, should the book include more material on coding itself? I would think fits best in Ch 2 ?

**Comment by luizaandrade** [comment]
Maybe we should create an appendix with links to resources?

**Comment by bbdaniels** [comment]
Let's not do this here
