### ISSUE TITLE
Ch7: data publication

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#281]
Need a clear framework for what gets covered in Ch1 vs what gets covered here in terms of reproducibility.

**Comment by mariaruth** [comment]
update to refer to the new AEA requirements?

**Comment by mariaruth** [comment]
separate data publication from publication of rep file. we can discuss, but my sense is that you would want the data up on microdata (or dataverse, we don't have to get into specifics of which repository) and code on github/ researcher website / etc. that way the data becomes citable as well.

**Comment by mariaruth** [comment]
worth mentioning that data de-identification for publication is not always straightforward! and may need to restrict access to data but still share code and perhaps metadata.

**Comment by mariaruth** [comment]
do we have an example of a well-structured public rep file that we could link to in the sidebar?

**Comment by kbjarkefur** [comment]
> update to refer to the new AEA requirements?

@bbdaniels will do this

**Comment by luizaandrade** [comment]
> Need a clear framework for what gets covered in Ch1 vs what gets covered here in terms of reproducibility.

Chapter 7 should be about how to make things available, not what the process is for making things replicable.

**Comment by kbjarkefur** [comment]
> separate data publication from publication of rep file. we can discuss, but my sense is that you would want the data up on microdata (or dataverse, we don't have to get into specifics of which repository) and code on github/ researcher website / etc. that way the data becomes citable as well.

This will be reflected in the new structure in #283

**Comment by kbjarkefur** [comment]
> worth mentioning that data de-identification for publication is not always straightforward! and may need to restrict access to data but still share code and perhaps metadata.

Merged with very similar comment in #283

**Comment by kbjarkefur** [comment]
> do we have an example of a well-structured public rep file that we could link to in the sidebar?

@luizaandrade  will find something
