### ISSUE TITLE
ch 7 : what is static projects?

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/d4di#285]
https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/chapters/publication.tex#L145-L147

What is static in this sentence?

**Comment by kbjarkefur** [comment]
Suggested edit:

_GitHub provides one of the easiest solutions to share a final product, since it is completely public projects[...]_

**Comment by bbdaniels** [comment]
Use this space to talk about the thinking behind it and to note that this is likely to change rapidly going forward
GitHub best for things that are not going to change, but not actually intended as an archive service
Archive services have third-party guarantee of availability and permanence

**Comment by bbdaniels** [comment]
ResearchGate, CodeOcean, OSF
