### ISSUE TITLE
Layout : vertical spacing in margin notes

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#29]
Right now, the margin notes are displayed as close to the text they refer to as possible. This often results in cluttered margins. If possible, adding some minimum space between would make it easier to find the corresponding note.

**Comment by bbdaniels** [comment]
I would love this but I do not know how to adjust the underlying document class to do it.

**Comment by kbjarkefur** [comment]
fixed in fa676ef , feel free to play around with the value
