### ISSUE TITLE
Ch5: Broken hyperlink

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#296]
Page not found - what was this supposed to link to? 
https://github.com/worldbank/d4di/blob/a9c4d76da0787053a59fee0c928001e04df648bc/chapters/data-collection.tex#L69

**Comment by bbdaniels** [comment]
should go here. are the `\` breaking it? https://iriss.stanford.edu/sites/g/files/sbiybj6196/f/questionnaire_design_1.pdf

**Comment by kbjarkefur** [comment]
I can't find this link in the most recent version of ch 5. Can we close this issue?

**Comment by luizaandrade** [comment]
I vote for closing

**Comment by mariaruth** [comment]
this was meant to get added back in. @bbdaniels maybe lost in the rewrite of ch 5? up to you Ben whether to include or close this issue

**Comment by bbdaniels** [comment]
Leave open for now. I need to go back and review links and add resources more generally.

**Comment by bbdaniels** [comment]
👍🏼

**Comment by bbdaniels** [comment]
Added link (502738a3e8fb7aa9d5c15673ac87f0b18bb9e34c). Chapter review to go to general review.

**Comment by kbjarkefur** [comment]
Great, Vote to close
