### ISSUE TITLE
Intro: check information about DIME Analytics start date

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#30]
Pretty sure it's been more like five than ten.

https://github.com/bbdaniels/d4di/blob/45bcc43eb6e7c3d168b4705cc16a7040b4d4d2f6/manuscript/chapters/introduction.tex#L37

**Comment by kbjarkefur** [comment]
I see your point, and I do not disagree, but you can argue that the experiences of this book builds on 10 years of experience in DIME. Not just us 4 exactly, and not just DIME Analytics.

**Comment by kbjarkefur** [comment]
July 2015 was when DIME Analytics was started.
