### ISSUE TITLE
CH 1 : obsolete link?

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/d4di#300]
In the section below we are linking to `http://datacolada.org` but as far as I understand we are not talking about that resource, is that a link to a resource we no longer are mentioning?

https://github.com/worldbank/d4di/blob/8b1108e4697adddcad86a2c7ad4e218b4864cef3/chapters/handling-data.tex#L216-L220

**Comment by luizaandrade** [comment]
I think this is just a general link about pre-registration. I quite like it, actually. I just think it it should come after this sentence:
https://github.com/worldbank/d4di/blob/8b1108e4697adddcad86a2c7ad4e218b4864cef3/chapters/handling-data.tex#L211-L214
