### ISSUE TITLE
Ch7: JPAL guide on publishing research data

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#301]
read and see if there's anything we want to reframe in our section given overlap (or lack thereof)
cite

https://www.povertyactionlab.org/sites/default/files/resources/J-PAL-guide-to-publishing-research-data.pdf

**Comment by luizaandrade** [comment]
👍

**Comment by bbdaniels** [comment]
Added link in 32e4bc87d97e3ea182588171d8e2bbc4c309e8c3 but no new content needed in chapter I think .
