### ISSUE TITLE
CH 5 - no side notes in full width intro

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/d4di#315]
In our current formatting rules we cannot have a sidenotes in the full-width introduction. See image below.

![image](https://user-images.githubusercontent.com/15911801/72391280-b6833f00-36fa-11ea-8f4e-c0a64aeb68a5.png)

Can they be moved to any later section? 

Here is where they are in the .tex file.

https://github.com/worldbank/d4di/blob/3f9cfe05b868d63e26c9575df680fa5e80bdb8f8/chapters/data-collection.tex#L8-L10

**Comment by mariaruth** [comment]
Good catch . the sidenote is shifted to later now.
