### ISSUE TITLE
Use LaTeX or TeX?

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/d4di#323]
Look up what is the exact difference between LaTeX and Tex? And then use them consistently across the bool.

**Comment by kbjarkefur** [comment]
TeX is the core language of LaTeX., see [here](https://tex.stackexchange.com/questions/49/what-is-the-difference-between-tex-and-latex) In TeX there is no predefined macors, so you have to code titles formatting, margins and everything else manually. In LaTeX there are macros and commands for that. So I guess that means that it is LaTeX everyone is using apart from some extreme exceptions. So lets use that

**Comment by kbjarkefur** [comment]
I do not find any instances of TeX anymore. I will close this issue, but the decision is to only write LaTeX and not TeX unless you refer to some uncommon and very technical use case of TeX/LaTeX.

**Comment by luizaandrade** [comment]
Should we keep this one open for future reference?
