### ISSUE TITLE
Ch5: collecting data securely - organization

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#324]
"secure data in the field" could just be joined with the following for as "secure data collection"; and the main section header could be "Handling data securely".

I don't follow the suggested restructure. Currently is:
Collection data securely
- Secure data in the field
- Secure data storage
- Secure data sharing

**Comment by mariaruth** [comment]
@bbdaniels or @kbjarkefur - i'm not sure who's comment this was in the review. i didn't understand it, if you still think it should be restructured let's discuss -- if not please close.

**Comment by kbjarkefur** [comment]
I am ok with closing this. It is likely something that is outdated by now anyway...
