### ISSUE TITLE
This side note defines Encryption differently than in Chapter 1. See below. Neither is incorrect, but should we be more consistent?

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#325]
Let's discuss and consolidate

This side note defines Encryption differently than in Chapter 1. See below. Neither is incorrect, but should we be more consistent?

https://github.com/worldbank/d4di/blob/7f842e62c725e64adc82d870515e2820bc6bb3e6/chapters/handling-data.tex#L351-L353

Also, the definition in the side note in this chapter is almost identical to what is being said in the next section on **Encryption at rest** anyways.

_Originally posted by @kbjarkefur in https://github.com/worldbank/d4di/pull/310_

**Comment by luizaandrade** [comment]
Same as #343
