### ISSUE TITLE
Is the _rule of three_ the same as what we call the _3-2-1 rule_ in chapter 2:

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#332]
Is the _rule of three_ the same as what we call the _3-2-1 rule_ in chapter 2:

https://github.com/worldbank/d4di/blob/17f55ca77a6e5b8ae594ea00c6fe1ad3926a861b/chapters/planning-data-work.tex#L91

_Originally posted by @kbjarkefur in https://github.com/worldbank/d4di/pull/310_

**Comment by kbjarkefur** [comment]
Close when #360 is closed
