### ISSUE TITLE
Ch 3 - randomize treatment vs control

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#334]
This is perhaps just a matter of perspective, but i think this is more intuitive from the opposite angle, i.e. to say: the 'treatment' being studied is randomly allocated-- that is, from an eligible population, a random subset of units are given access to the treatment. The non-selected units serve as a counterfactual.

_Originally posted by @mariaruth in https://github.com/worldbank/d4di/diffs/1_

**Comment by kbjarkefur** [comment]
@bbdaniels 
> I think you are right that it is more intuitive the other way, but I described it this way because I think it is important to take a moment to understand that this is why. I want people to stop and think while reading this section -- thinking of it as selecting the counterfactual at random from the eligible is a nice brain stretch IMO

**Comment by luizaandrade** [comment]
👍

**Comment by bbdaniels** [comment]
This is rewritten in https://github.com/worldbank/d4di/pull/382/commits/7f4816fb6786d6076bc04191d3ba533d82054cb1 for clarity. Vote to close.
