### ISSUE TITLE
Review all section headers

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#336]
Check all section headers 
* wording is clear
* tense is consistent
* alignment of sections and subsections

---------
basically, "why some common designs give valid estimates". not sure how to reword at the moment...

_Originally posted by @bbdaniels in https://github.com/worldbank/d4di/diffs/1_

**Comment by kbjarkefur** [comment]
for example: https://github.com/worldbank/d4di/blob/43b19d12da22e76d861f6eb3c004a4decf6f60d0/chapters/research-design.tex#L227
