### ISSUE TITLE
Crossed content in chapters 5 and 7

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#342]
Most of this content is already in chapter 7. I think that chapter is a better fit for it, but we need to make sure that all content is there, particularly with regards to the sidenotes.

_Originally posted by @luizaandrade in https://github.com/worldbank/d4di/diffs_

**Comment by bbdaniels** [comment]
I think this is redundant in a good way since these should stand independently of each other and it is not duplication. Vote to close.

**Comment by luizaandrade** [comment]
Agreed.
