### ISSUE TITLE
[ch5] link to data security instructions

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#344]
on the wiki or in dime standards

_Originally posted by @kbjarkefur in https://github.com/worldbank/d4di/diffs_

**Comment by kbjarkefur** [comment]
I don't understand this issue and the link does not load for me.

**Comment by mariaruth** [comment]
link doesn't load for me either. @kbjarkefur are you satisfied with the content on data security in Ch 5 given your recent work with the security standards? if so, i think we can close the issue.

**Comment by luizaandrade** [comment]
Ha! I guess because the PR was closed the issues that were opened from review comments are not linked anymore. I still think we should link to the instructions, though, as we don't discuss them in detail in the book

**Comment by kbjarkefur** [comment]
I have linked to what we have made public. I do not know if we want to make the DIME-standards repo public at this point as there is only the main README, the checklists and the data security material. 

@luizaandrade , you self-assigned, what are you thinking?

**Comment by luizaandrade** [comment]
I think this is enough to make the repo public. But about this issue in particular I think that linking to the Wiki is preferred. So closing it.
