### ISSUE TITLE
ch 7 - restructuring the dynamic document section

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/d4di#348]
@kbjarkefur 
I think the section on LaTeX should come before the section with tools such as DropBox paper, Rmarkdown and dyndoc, as LaTeX has proven to not be a fad and has been the staple of this for decades.

 @bbdaniels
It's currently after because it is a special case of dynamic document. I don't see how it could be reversed, but I clarified a bit in a68c08b. Improvements here welcome.

 @mariaruth
In terms of structure, i think it would be useful to tie these tools into a workflow. Something like - dynamic docs are helpful for exploratory analysis / preparing intermediate outputs, but latex is best practice for the actual manuscript.

**Comment by kbjarkefur** [comment]
https://github.com/worldbank/d4di/blob/177316c4719c315084f2e95de24af00e1c4ff69b/chapters/publication.tex#L240

@mariaruth
Would this level of detail fit better into a wiki page than the main text of the book? it's a general question for us to keep in mind, i think the level of detail varies quite a bit across chapters.

 @bbdaniels
bbdaniels 7 days ago Author Member
I think this might be important enough to include in the text, but maybe could be sidebarred

**Comment by kbjarkefur** [comment]
👍 , if we allow our self slightly larger discussions at this moment, then I think this should be included

**Comment by mariaruth** [comment]
Restructured a little in #399, i think this flows more clearly now. @bbdaniels @kbjarkefur if you approve, close the issue.

**Comment by kbjarkefur** [comment]
I approve closure, I liked this order much better
