### ISSUE TITLE
Data licensing agreements AND include primary data from partners

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#351]
We need to cover this -- better to do so in Ch1, Ch5 or Ch7? 
---

Add here the importance of establishing a data licensing agreement if directly acquiring data from partners (e.g. administrative data that is not otherwise public, or proprietary data from firms, etc).

_Originally posted by @mariaruth in https://github.com/worldbank/d4di/pull/293_

**Comment by bbdaniels** [comment]
I think this is going to be best put into Chp 5 by @mariaruth. I think we will want to add a section on "primary data that is not survey data" before getting into the survey sections. So "collecting primary data from partners" or some such. What do you think?

**Comment by bbdaniels** [comment]
Namely, Chp 5 would get one more major section, and break down as follows:

1. Collecting primary data from development partners
    1. Data licensing agreements
    1. Data ownership agreements
    1. Receiving data from partners
1. Collecting primary data using field surveys
    1. Survey development
    1. Designing electronic questionnaires
    1. Programming electronic questionnaires
1. Data quality assurance and security
    1. High-frequency checks (extend to ongoing data intake from partners)
    1. Back-checks and validation (extend to confirming received data)
    1. Receiving, storing, and sharing data securely

**Comment by mariaruth** [comment]
Yes - this is a great way to reframe to cover all types of data. worth noting that data license / ownership discussions/ agreements should also happen around data being collected (especially if research team is not financing directly)

**Comment by bbdaniels** [comment]
Great. I will take this on today.

**Comment by mariaruth** [comment]
Reminder to update chapter preview in intro when we are done with this rewrite.

**Comment by kbjarkefur** [comment]
I think we have enough content on security to keep a section on that. See section 4 below. And @luizaandrade wants to move initial de-identification to chapter 6 and de-identification for publication to chapter 7, and I agree with that.

1. Collecting primary data from development partners
    1. Data licensing agreements
    1. Data ownership agreements
    1. Receiving data from partners
1. Collecting primary data using field surveys
    1. Survey development
    1. Designing electronic questionnaires
    1. Programming electronic questionnaires
1. Data quality assurance
    1. High-frequency checks (extend to ongoing data intake from partners)
    1. Back-checks and validation (extend to confirming received data)
1. Collecting and sharing data securely
    1. Secure data in the field
    1. Secure data storage -- during data collection
    1. Secure data storage -- after data collection
    1. Secure data sharing and publication

**Comment by luizaandrade** [comment]
I agree that data quality assurance and data security should be separate. I think section 4.iv should be short and mostly recap content on secure data sharing from chapter 1 as well as refer to chapter 7 on secure data publication.

**Comment by bbdaniels** [comment]
This is done by 2f9330014f1c73d64ca813199c2361643871181; final review has a new issue in #378. Closing.
