### ISSUE TITLE
[ch7] book conclusion

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#354]
Chapter 7 should link to the other chapters
- Publication is the final step and the end goal of the research process
- If the project followed the guidelines outlined in this book, this should be a relatively easy process, creating a replication is package is relatively straightforward

**Comment by bbdaniels** [comment]
draft in https://github.com/worldbank/d4di/pull/357 -- kept on the short side and know it needs edits/cleanup but want feedback on direction. it is very simple text.
