### ISSUE TITLE
Crossed content in chapters 2 and 6

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#355]
The section called 'organizing code and data' in chapter 2 has some overlap with chapter 6. I think we should have a new section in chapter 2 about why we write code (#178) and how to write good code, that gives general advice but doesn't go into much detail (content of the programming 101 session):
- Why do we write code?
- The critical thinking of data: 
Do I believe this number? What can go wrong in my code? How will missing values be treated in this command? What would happen if more observations would be added to the data set?
- Generalize your code! DRY, loops, functions
- Better to use pre-existing commands that you trust than writing your own

**Comment by bbdaniels** [comment]
I would suggest Chp. 6 if we still want to integrate this content. 👍🏼

**Comment by kbjarkefur** [comment]
What about putting this in the Stata appendix?
