### ISSUE TITLE
ch 2 - side note way too long

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/d4di#361]
https://github.com/worldbank/d4di/blob/f92501088009fd11a42e9cedd99b26fdd818e3a1/chapters/handling-data.tex#L89

@bbdaniels , can this side note be made shorter? it is pushing things of the page.

**Comment by bbdaniels** [comment]
would any of those references fit in other places so we can spread them out? I want to have them all but I know they are long references.

**Comment by kbjarkefur** [comment]
I do not know the content of those sources, but if you think they could fit somewhere else, then that seems like a good solution to me.

**Comment by bbdaniels** [comment]
👍🏼

**Comment by luizaandrade** [comment]
We will leave this to the final final review because it involves the typesetting and displaces things
