### ISSUE TITLE
Standardize use of bold text

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#365]
We need to discuss what should be bolded and make the use consistent across the book.

**Comment by kbjarkefur** [comment]
I have been thinking that as well, but I was thinking that is what the professional editors are experts on. We use bold, italic, underline, and quotation marks in very different ways across the book.

**Comment by luizaandrade** [comment]
Happy to leave that for the editors. But I think it's still useful to have the issue so we remember to check for that.

**Comment by luizaandrade** [comment]
Close

**Comment by kbjarkefur** [comment]
Close and let professional editors deal with it
