### ISSUE TITLE
Mention DIME collection on microdata catalog

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#371]

**Comment by bbdaniels** [comment]
👍🏼

**Comment by luizaandrade** [comment]
It's up now!!
Internal facing catalog under Specialized Collections  here: https://microdatalib.worldbank.org/index.php/catalog/central/about
External facing catalog under World Bank Contributing Catalogs  here:  https://microdata.worldbank.org/index.php/catalog/central/about

**Comment by kbjarkefur** [comment]
This is the link we should use, right? https://microdata.worldbank.org/index.php/catalog/dime/about

We can remove the implementation specific `index.php` and only use https://microdata.worldbank.org/catalog/dime/about

**Comment by mariaruth** [comment]
I think it's fine to link directly to the data
