### ISSUE TITLE
Final review for Chapter 5

### ISSUE THREAD

**Issue by bbdaniels** [worldbank/d4di#378]
@mariaruth to review Chapter 5 language and resources on separate branch. Hopefully this is the last thing before the review version!

**Comment by mariaruth** [comment]
@bbdaniels should i create the branch for bbd-ch5 or wait until that is merged to develop?

**Comment by bbdaniels** [comment]
I thought it is merged already? You should be able to create a new branch off `develop`. Let me know if that's not working.

**Comment by mariaruth** [comment]
ok, for some reason bbd-ch5 is still showing up for me but content is the same as develop, i'll create from there.

**Comment by kbjarkefur** [comment]
`bbd-ch5` was just this second removed. It might be ok to use that branch, but since other branches has been merged to `develop` it is much better practice to create a new branch from `develop`

**Comment by bbdaniels** [comment]
Yep just went through and cleaned branches that should have been deleted.

Best,

Ben

**Comment by kbjarkefur** [comment]
> Yep just went through and cleaned branches that should have been deleted.

Ok, I hope that does not create something odd 🤞 as @mariaruth said:

> ok, for some reason bbd-ch5 is still showing up for me but content is the same as develop, i'll create from there.

**Comment by mariaruth** [comment]
addressed in cf99b8226eef4ea38d6f547382f4ed9678d3e53d and ece359f9973cc7b801b683df73ed67600117316c
