### ISSUE TITLE
[stata appendix] - unnecessarily complicated word

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/d4di#379]
Oh the joy listing this word as unnecessarily complicated given what the rest of the sentence says! 🤣 🍾 🙈 

- [x] corollary

https://github.com/worldbank/d4di/blob/922e786c04bba5fb67ae14edf0373ad8c7049a3a/appendix/stata-guide.tex#L149-L151

**Comment by bbdaniels** [comment]
a8198d46af8858953898995e3cb53c32d67b5ed6
