### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/d4di#383]
These links are broken. Whoever recognize the link, see how it can be fixed:

- [x] fixed

https://github.com/worldbank/d4di/blob/dc91a4d50a3dece209436b0933fd2cd58f6deb76/bibliography.bib#L59-L61

---

- [x] fixed

https://github.com/worldbank/d4di/blob/dc91a4d50a3dece209436b0933fd2cd58f6deb76/chapters/planning-data-work.tex#L449-L451

---

- [x] fixed

https://github.com/worldbank/d4di/blob/dc91a4d50a3dece209436b0933fd2cd58f6deb76/chapters/research-design.tex#L428-L430

---

- [x] fixed

https://github.com/worldbank/d4di/blob/dc91a4d50a3dece209436b0933fd2cd58f6deb76/chapters/research-design.tex#L467-L469

**Comment by bbdaniels** [comment]
Stock and Yogo: https://scholar.harvard.edu/files/stock/files/testing_for_weak_instruments_in_linear_iv_regression.pdf

Jenny Bryan: http://www2.stat.duke.edu/~rcs46/lectures_2015/01-markdown-git/slides/naming-slides/naming-slides.pdf

Patricia Baumer: http://faculty.smu.edu/kyler/courses/7312/presentations/baumer/Baumer_RD.pdf

Bond: http://www.nuff.ox.ac.uk/teaching/economics/bond/IV%20Estimation%20Using%20Stata.pdf

**Comment by kbjarkefur** [comment]
My bad on 3 & 4, I tested many URLs and got sloppy when looking for escape characters.

Fixed in 456e62067b6d7a0595f0747e477758485b84a14f. 1 & 2 are updated as you suggested. 2, 3 and 4 are changed from `http` to `https`
