### ISSUE TITLE
Ch1: transmitting and storing data securely

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#385]
The below section feels too granular for this chapter. i suggest we cut from here and make sure the details are covered in later chapters. since this is consistent with what we agreed in #160, i made this change in 7ea682450649f5942cb1d9c660aef302f91f5c21 but if @kbjarkefur or @bbdaniels you disagree please revert. 

> The biggest security gap is often in transmitting survey plans to and from staff in the field.
>To protect information in transit to field staff, some key steps are:
>(a) ensure that all devices that store confidential data
>have hard drive encryption and password-protection;
>(b) never send confidential data over email, WhatsApp, or other chat services.
>without encrypting the information first; and
>(c) train all field staff on the adequate privacy standards applicable to their work.

**Comment by kbjarkefur** [comment]
When reading this I agree that it changed pace a bit, which was odd, but I do think this sentence is important to keep somewhere.

> never send confidential data over email, WhatsApp, or other chat services.
without encrypting the information first

I'd like to keep more, but I know I am biased towards this topic. I think that staff in field, especially non-WB field partners, is the biggest security risk, but we do not have targeted resources for them yet. We just created resources for ourselves.

Would combining a) and b) into one sentence be a compromise. 

Here is link for context (note that the version this link points to is outdated now, so do not make edits there):
https://github.com/worldbank/d4di/blob/047a8c10348129b300493ccdfd61be78d1cff566/chapters/handling-data.tex#L344-L355

**Comment by mariaruth** [comment]
@kbjarkefur i was not thinking of getting rid of this information, just moving it to the wiki -- that seems quite accessible to field partners? If you agree let's keep this open with a wiki flag. 

Happy to keep a sentence, but i wasn't very clear from the above if you wanted the sentence quoted or some other combination of a) and b). Please go ahead and suggest the change directly.

**Comment by kbjarkefur** [comment]
This is already on the wiki, but I think it is important enough to be mentioned in the book. I agree that it before was odd in some way of granularity and that it was expressed in a list.

What about this: bfc1493a2e1ee92a6717a047c2ec1ed2a16065af 

It is in the end of that paragraph as a final item, instead of being whats opening the paragraph. Let me know if you think this works better.
