### ISSUE TITLE
Ch1: storing raw, identified data

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#386]
> There should only be one raw identified dataset copy and it should be somewhere where only approved people can access it.

Really only 1? since we otherwise recommend 3 should clarify

**Comment by kbjarkefur** [comment]
Quote comes form here: 
https://github.com/worldbank/d4di/blob/2adf384887cf93bb2fa2855c7634acf50c94e59e/chapters/handling-data.tex#L412-L417

We need to clarify. We should have one copy + 2 back-ups. What about:

> There should never be more than one copy of the raw identified dataset in the project folder, and it must always be encrypted.

**Comment by mariaruth** [comment]
addressed in 9b31ac32630637abe6d169909c111a42737a2753
