### ISSUE TITLE
Ch2

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#395]
"just like the standard restriction of each line to 80 characters" --> i do not think 80 chars is standard to a general audience! 

https://github.com/worldbank/d4di/blob/8b98e52c899291a674ce23ea3174fdc4d349126d/chapters/planning-data-work.tex#L542

**Comment by kbjarkefur** [comment]
solved in 44ee2f4efc2ea0ee9c6378d264cd6367b8a8fc4e
