### ISSUE TITLE
Ch 2: version control is not a method for file sharing

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#430]
This sentence is confusing two different concepts. GitHub allows us to share files because of its syncing features. You cannot share files using Git. 

I suggest making version control a separate paragraph.

https://github.com/worldbank/d4di/blob/f901bdd71bc018a13744e28359426b1977be86af/chapters/planning-data-work.tex#L131

I also don't think file sharing is the main reason why people use servers, but have less strong feelings about that

**Comment by mariaruth** [comment]
made version control a new subsection in ch2 rewrite
