### ISSUE TITLE
Ch 2: remove reference to Kanban?

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#431]
Kanban is about managing tasks in a board with columns, though a lot of Kanban-based applications allow for documentation _and_ task management. I think this paragraph is a little bit confusing in mixing task management and documentation.

https://github.com/worldbank/d4di/blob/f901bdd71bc018a13744e28359426b1977be86af/chapters/planning-data-work.tex#L179

**Comment by mariaruth** [comment]
removed in re-write of ch2
