### ISSUE TITLE
add abbreviation page

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/d4di#54]
current abbreviations (comment in this thread for more abbreviation):

- FC - field coordintor
- RA - research asisistant
- PI - Principal investoigator - the senior researcher in charge of the projcets
- PII - Personally indentifiable information

**Comment by kbjarkefur** [comment]
we want this list even if it is short, as it will make people suggest what we are missing

**Comment by bbdaniels** [comment]
Done in 8ee8f6d976855de8c89212dfb0e1432cac7aa21d
