### ISSUE TITLE
Ch1: handling data ethically suggestions

### ISSUE THREAD

**Issue by LeonardoViotti** [worldbank/d4di#82]
- [x] Add brief explanation for each concept introduced.

There are many concepts or references (e.g. Github, pre-analysis plan and encryption) that may be completely new to the reader. It is nice to have references in case they want to understand these concepts in depth, but there must be some simple explanation so they can follow the text without having to look at other materials.

- [ ] Better address data privacy and security. 

I believe the chapter addresses well the research community and transparency side of handling data ethically, but barely touches the human subjects part of it. 

There is an intrinsic trade-off between transparency and privacy that the chapter completely ignores. The section that does talk about privacy and security is very short and fails to portray the complexity of the issue. It almost sounds like "if you encrypt your data and de-identify it, you're good to go". It mentions tools, doesn't explain them or get into the practical steps to use them.

**Comment by luizaandrade** [comment]
I completely agree with the first point. I tried to mark cases where this happens when I first reviewed the book in issue #32. It would probably be better for someone who's part of our intended audience to mark the concepts they're not familiar with, so I have reopened the issue and will ask Radhika or Yifan to do this.

**Comment by luizaandrade** [comment]
@LeonardoViotti On your second point, do you have a suggestion of what are good resources to link to? Would also be helpful if you could share a quick skeleton structure of what should be included there for us to start working from.

**Comment by LeonardoViotti** [comment]
Here's a draft suggestion of structure. Or at least topics I think should be covered.

1. Research Ethics - Doesn't need to be too long, but a brief overview of the main concepts would be nice. Some suggested topics are:
- Human subjects 
- Consent
- The right to privacy

2. Replicability  and transparency - I think this is already fairly addressed in the current version, but I would add a little bit about the trade-offs between transparency and privacy.

3. Data security - Some of the suggested topics:
- Data handling and encryption
- De-identification and de-identification of GIS data
- Inherent risks - something in the lines of:
  -  " there is no perfect security"
  -  what you need to be careful with
  -  what are the trade-offs (adding noise to the data for example) and that are datasets that simply cannot be completely de-identified.

**Comment by mariaruth** [comment]
Some of point 3 in Leo's outline above overlap with the 'Collecting Data Securely' section of Ch 6: Collecting Primary Data (specifically data handling and encryption). Should we move that section to Ch 2?

**Comment by mariaruth** [comment]
On point 1 above, also add ethical clearance (IRB) - now this only comes us in the 'collecting data securely' section of ch. 6

**Comment by bbdaniels** [comment]
> Here's a draft suggestion of structure. Or at least topics I think should be covered.
> 
> 1. Research Ethics - Doesn't need to be too long, but a brief overview of the main concepts would be nice. Some suggested topics are:
> 
> * Human subjects
> * Consent
> * The right to privacy
> 
> 1. Replicability  and transparency - I think this is already fairly addressed in the current version, but I would add a little bit about the trade-offs between transparency and privacy.
> 2. Data security - Some of the suggested topics:
> 
> * Data handling and encryption
> * De-identification and de-identification of GIS data
> * Inherent risks - something in the lines of:
>   
>   * " there is no perfect security"
>   * what you need to be careful with
>   * what are the trade-offs (adding noise to the data for example) and that are datasets that simply cannot be completely de-identified.

1 and 2 into this chapter, plus "what are the trade-offs". The rest of the actual handling into Ch6. Also -- title change as noted in #150

**Comment by luizaandrade** [comment]
Some more things that I think we should discuss in this chapter:
- Avoid the proliferation of copies of identified data
- Not everyone needs access to identified data
- Only information that is strictly needed for research should be collected
- This may depend on where you work, but research team members are typically liable for how they handle the data
- Data security is important not only for identified, but also sensitive information

**Comment by kbjarkefur** [comment]
@bbdaniels will do the edits that goes into chapter 2.

@RadhikaKaul , for the remaining points that will go into chapter 6, can you open a new issue with Ch6 label with just those point? Please refer back to this issue

**Comment by luizaandrade** [comment]
All this content has been incorporated into chapter 1
