### ISSUE TITLE
Ch 2: IE folder structure

### ISSUE THREAD

**Issue by RadhikaKaul** [worldbank/d4di#83]
Summary-
- [ ] While IE folder structure primarily caters to a team working with primary data, is there a way to address/extend the usage of IE folder structure for a team working with secondary data and perhaps address the distinct usage (if any) in the book?
- [ ]  Additional folders for codes apart from do files(ex. R) could be useful.

From @aram92:

> - The IEfolder structure is very well made but mainly adapted to primary data. Now, generally as FC start their mission, they are mainly faced with secondary data and a great share of work is done with those. From my previous experience and from what I am seeing now while transitioning the IEConnect Senegal project into the IEFolder, it is not straightforward to align the organization of secondary data into that structure. Thus, while I would start by mentioning in the handbook that the suggestion of that structure is more adapted to primary data, I am also curious to know if you think that we could work on developing a component of the IEtoolkit package that would create a specific path for secondary data? For example, what we are thinking of doing now for Senegal, is to have within each round a folder for primary data, which would have the usual folders (dataset, documentation, dofiles, output, questionnaire) and one for secondary data, which would be more personalized for each project but would generally have: raw data, cleaned data, documentation, output. We are still working on improving it but the main confusion came from the fact that we wouldn’t know exactly where to store raw secondary data that do not need encryption most of the time. Plus for some of the output where we need to have data and code in the same folder (like Shiny apps), we would create a specific folder for that particular output.
> - In the IE folder structure, I think it could be useful within each round to have a folder for codes other than do files (like R codes).

**Comment by kbjarkefur** [comment]
@kbjarkefur add to wiki that one round should be considered one data source
