### ISSUE TITLE
Ch 2: Folder management for incoming RAs

### ISSUE THREAD

**Issue by RadhikaKaul** [worldbank/d4di#84]
From Aram:

> Since RA and FC come into a project when generally a shared folder already exists, I think that it is worthy at some point to insist on the fact that the folder creators (TTLs and external PI most of the time), start with a clear structure upfront so that when assistants take over, not many restructuring would be needed. Having a continuing education session targeted to TTL on the matter may be useful.

**Comment by kbjarkefur** [comment]
Combined with : #201
