### ISSUE TITLE
Ch 3: Suggestions for DiD section 

### ISSUE THREAD

**Issue by RadhikaKaul** [worldbank/d4di#90]
From Caio:

> In the diff-in-diff section, I think you could make a quick mention to the overlooked assumptions such as strict exogeneity. If the treatment was based on past realizations of the outcomes (e.g. test score, profits, land productivity etc.), the strict assumption does not hold and diff-in-diff won’t result in unbiased estimates even if parallel trends are observed. Selection is based on past realization of the outcome, not on time invariant fixed effects. In those case, an ANCOVA specification would be preferred. A good source for this discussion is Morgan and Winship Counterfactual and Causal Analysis.

**Comment by kbjarkefur** [comment]
Will be added to Ancova issue in #221
