### ISSUE TITLE
Ch 3: Suggestions for RDD section

### ISSUE THREAD

**Issue by RadhikaKaul** [worldbank/d4di#91]
From Caio:

> - Should RDD come under experimental research designs?
> - In this section you could say that the running variable is also referred to as assignment variable or forcing variable.
> - I don’t think the RD design is usually justified on budget grounds. It is rather a consequence of a policy change that artificially discriminates against some subgroup. I read recently on twitter that ‘every time we see a discontinuity it’s because there is a distortionary policy behind.’ I tend to agree with that, but don’t think you want to say that in the book!

**Comment by kbjarkefur** [comment]
* We removed the experimental design section header
* No
* We agree with Caios point. Include.
